// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://npuxtzuxnfccflphdlxj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5wdXh0enV4bmZjY2ZscGhkbHhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1MTE2MzAsImV4cCI6MjA2OTA4NzYzMH0.5sq4hDNmNbf9cDxyxZ_sC94eLeLyg2ha9niMqo_CNPQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});